server:
  port: 8001

spring:
  application:
    name: simple-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ikos23/learning-spring-cloud
          search-paths:
            - config-repo
          basedir: gitbasedir

logging:
  level:
    org:
      springframework: INFO


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/,http://localhost:8766/eureka/
