server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ikos23/learning-spring-cloud
          search-paths:
            - config-repo
          basedir: gitbasedir

logging:
  level:
    org:
      springframework: INFO
